accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = 'accountapp'

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'),
         name='login'),
    path('logout/', LogoutView.as_view(), name='logout' ),

    path('create/', AccountCreateView.as_view(), name='create'),

    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),

    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete')
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

temp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accountapp/models.py
from django.db import models

# Create your models here.
class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.



class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL,
                               related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=True)
    content = models.TextField(null=True)

    created_at = models.DateTimeField(auto_now_add=True, null=True)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                related_name='profile')
    image = models.ImageField(upload_to= 'profile/', null=True)
    nickname = models.CharField(max_length=30, unique=True)
    message = models.CharField(max_length=200, null=True)

articleapp/forms.py
from django.forms import ModelForm

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'image', 'content']

profileapp/forms.py
from django.forms import ModelForm

from profileapp.models import Profile


class ProfileCreationForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.decorators import account_ownership_required
from accountapp.form import AccountCreationForm
from accountapp.models import HelloWorld

@login_required(login_url=reverse_lazy('accountapp:login'))
def hello_world(request):
    if request.method == "POST":

        temp = request.POST.get('input')
        new_data = HelloWorld()
        new_data.text = temp
        new_data.save()

        return HttpResponseRedirect(reverse('accountapp:hello_world'))

    else:
        data_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html',
                      context={'data_list': data_list})



class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'accountapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

has_ownership = [login_required, account_ownership_required ]

@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')

class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountCreationForm
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')

class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/delete.html'

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleCreationForm
    template_name = 'articleapp/create.html'

    def form_valid(self, form):
        form.instance.writer = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


class ArticleDetailView(DetailView):
    model = Article
    context_object_name = 'target_article'
    template_name = 'articleapp/detail.html'


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleCreationForm
    context_object_name = 'target_article'
    template_name = 'articleapp/update.html'

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    model = Article
    context_object_name = 'target_article'
    success_url = reverse_lazy('articleapp:list')
    template_name = 'articleapp/delete.html'

class ArticleListView(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = 20

profileapp/views.py
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from profileapp.decorators import profile_ownership_required
from profileapp.forms import ProfileCreationForm
from profileapp.models import Profile

class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileCreationForm

    template_name = 'profileapp/create.html'

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

@method_decorator(profile_ownership_required, 'get')
@method_decorator(profile_ownership_required, 'post')
class ProfileUpdateView(UpdateView):
    model = Profile
    context_object_name = 'target_profile'
    form_class = ProfileCreationForm
    template_name = 'profileapp/update.html'



    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.user.pk})

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4> Sign up</h4>

            </div>
            <div>

                <form action="{% url 'accountapp:create' %}" method="post">
                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4> Quick </h4>

            </div>
            <div>

                <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
                    {% csrf_token %}

                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">
                {% if target_user.profile  %}
                    <img src="{{ target_user.profile.image.url }}"
                         class="profile_image= m-4"
                         alt="profile image">
                        <h2 class="NNS_B">
                            {{ target_user.profile.nickname }}
                            {% if target_user == user %}
                            <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}"
                                class="material-icons round_button">
                                edit
                                </a>
                                {% endif %}
                        </h2>
                        <h5>{{ target_user.profile.message }}<h5>
                {% else %}
                <h4>
                    <a href="{% url 'profileapp:create' %}">
                        Create Profile
                    </a>
                </h4>
                {% endif %}
            </div>

            {% if user == target_user %}
            <div>
                <a href="{% url 'accountapp:update' pk=target_user.pk %}"
                class="material-icons round_button mx-1">
                   settings
                </a>

                <a href="{% url 'accountapp:delete' pk=target_user.pk %}"
                class="material-icons round_button mx-1">
                   close
                </a>
            </div>
            {% endif %}

    </div>




{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}



</style>
    <div style="margin: 2rem; text-align: center">
        <h1>METHOD</h1>

        <form action="/accounts/hello_world/" method="post">
            {% csrf_token %}
            <input type="text" name="input">
            <input type="submit" class="btn btn-dark rounded-pill px-5">
        </form>

        {% for data in data_list %}
        <h3>{{ data.text  }}</h3>{#단순 변수 출력은 {{  }} 를 사용함#}
        {% endfor %}
    </div>

{% endblock content %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}


    <div class="text-center  mw-500 m-auto">

              <div class="m-5">

                <h4>Login</h4>

            </div>
            <div>

                <form action="{% url 'accountapp:login' %}" method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4> Updata Info</h4>

            </div>
            <div>

                <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4>Create Article</h4>

            </div>
            <div>

                <form action="{% url 'articleapp:create' %}"
                      method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}


    <div class="text-center mw-500 m-auto">
        <div class="m-5">
            <h4>Delete Article : {{ target_article.title }}</h4>
        </div>
        <div>
            <form action="{% url 'articleapp:delete' pk=target_article.pk %}"
                  method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="m-5">
                    <input type="submit"
                       class="btn btn-danger rounded-pill px-5">
                </div>
            </form>
        </div>
    </div>


{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}


    <div class="container text-center">
        <div class="my-5">
            {#      게시글 제목, 글쓴이, 작성일자      #}
            <h1 class="NNS_B">{{ target_article.title }}</h1>
            <h4>{{ target_article.writer.profile.nickname }}</h4>
            <p>{{ target_article.created_at }}</p>
        </div>

        <hr>

        <div class="my-5">
            {#      게시글 내용, 게시글 대표 이미지      #}
            <img src="{{ target_article.image.url }}"
                 class="article_image"
                 alt="">
            <div class="article_content my-5">
                {{ target_article.content }}
            </div>
            {% if target_article.writer == user %}
            <div>
                <a href="{% url 'articleapp:update' pk=target_article.pk %}"
                   class="btn btn-success rounded-pill px-5">
                    Update
                </a>
                <a href="{% url 'articleapp:delete' pk=target_article.pk %}"
                   class="btn btn-danger rounded-pill px-5">
                    Delete
                </a>
            </div>
            {% endif %}
        </div>
    </div>


{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>
        .container div {
          width: 280px;
          display: flex;
          justify-content: center;
          align-items: center;
          border-radius: 1rem;
            flex-direction: column;
            box-shadow: 0 0 1rem gray;
        }

        .container img {
            width: 100%;
            border-radius: 1rem;
        }
    </style>


    <div class="container my-4">

        {% for article in article_list %}

            <div>
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    <img src="{{ article.image.url }}" alt="">
                </a>
                <span class="my-2 NNS_B">{{ article.title }}</span>
            </div>

        {% endfor %}

    </div>

    <script src="{% static 'js/magicgrid.js' %}"></script>


{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4>Update Article</h4>

            </div>
            <div>

                <form action="{% url 'articleapp:update' pk=target_article.pk %}"
                      method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

profileapp/templates/profileapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4>Create Profile</h4>

            </div>
            <div>

                <form action="{% url 'profileapp:create' %}"
                      enctype="multipart/form-data"
                      method="post">

                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

profileapp/templates/profileapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}


    <div class="text-center mw-500 m-auto">

            <div class="m-5">

                <h4>Update Profile</h4>

            </div>
            <div>

                <form action="{% url 'profileapp:update' pk=target_profile.pk %}"
                      enctype="multipart/form-data"
                      method="post">

                    {% csrf_token %}
                     {% bootstrap_form form %}
                    <div class="m-5">
                            <input type="submit"
                           class="btn btn-dark rounded-pill px-5">
                    </div>


                </form>

            </div>



    </div>




{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">


{% include 'head.html' %}

<body style="font-family: 'NanumSquareR' ">

{% include 'header.html' %}

<hr>

{% block content %}
{% endblock %}

<hr>

{% include 'footer.html' %}

</body>
</html>

templates/footer.html
<div style="text-align: center">

    <div class="pragmatic_footer_botton">
        <span>공지사항</span>
        <span>제휴문의</span>
        <span>서비스 소개</span>
    </div>
<div class="pragmatic_footer_logo">
    <h5>Pragmatic</h5>
</div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <title>Title</title>

    {#  BOOTSTARP LINK  #} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
                                 integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {# GOOGLE FONT LINK #}
        <link rel="preconnect" href="https://fonts.googleapis.com">

        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    {# MATERIAL ICONS LINK #}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">

    <style>
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR'),
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB'),
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB'),
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL'),
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
    </style>

</head>

templates/header.html
<div style="text-align: center">
    <div class="pragmatic_header_logo">

        <h1>Pragmatic</h1>

    </div>
    <div class="pragmatic_header_botton">
        <span>nav1</span>
        <span>nav2</span>

        {% if not user.is_authenticated %}
        <span>
            <a href="{% url 'accountapp:login' %}">
                Login
            </a>
        </span>

        <span>
            <a href="{% url 'accountapp:create' %}">
                Signup
            </a>
        </span>
        {% else %}

            <span>
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
            MyPage
            </a>
        </span>

            <span>
            <a href="{% url 'accountapp:logout' %}">
            Logout
            </a>
        </span>
        {% endif %}
    </div>

</div>